import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../features/settings/providers/settings_provider.dart';

class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  bool get isMalayalam => language == 'Malayalam';

  static final Map<String, String> _ml = {
    // Navigation & App Bar
    'Home': 'ഹോം',
    'My Kuris': 'എന്റെ ചിട്ടികൾ',
    'Chitties Catalog': 'ചിട്ടി കാറ്റലോഗ്',
    'Explore Chitties': 'ചിട്ടികൾ കാണുക',
    'Payments & Passbook': 'പാസ്ബുക്ക് & പേയ്‌മെന്റുകൾ',
    'My Profile': 'എന്റെ പ്രൊഫൈൽ',
    'Settings': 'സെറ്റിംഗ്സ്',
    'Notifications': 'അറിയിപ്പുകൾ',
    'Good Morning,': 'സുപ്രഭാതം,',
    'Welcome Back': 'വീണ്ടും സ്വാഗതം',
    'Kerala Kuri': 'കേരള കുറികൾ',
    'Official Chitty Ledger': 'ചിട്ടി ലെഡ്ജർ',

    // Period & Filter Chips
    'All': 'എല്ലാം',
    'Monthly': 'മാസം',
    'Weekly': 'ആഴ്ച',
    'Yearly': 'വർഷം',
    'All Chitties': 'എല്ലാ ചിട്ടികളും',
    'New Chitties': 'പുതിയ ചിട്ടികൾ',
    'Joined Chitties': 'ചേർന്ന ചിട്ടികൾ',
    'Already Joined': 'ചേർന്നവ',
    'View All': 'എല്ലാം കാണുക',

    // Pre-calculated filter chip counts for O(1) constant time lookup
    'All (0)': 'എല്ലാം (0)',
    'All (1)': 'എല്ലാം (1)',
    'All (2)': 'എല്ലാം (2)',
    'All (3)': 'എല്ലാം (3)',
    'All (4)': 'എല്ലാം (4)',
    'All (5)': 'എല്ലാം (5)',
    'All (6)': 'എല്ലാം (6)',
    'All (7)': 'എല്ലാം (7)',
    'All (8)': 'എല്ലാം (8)',
    'Active (0)': 'സജീവം (0)',
    'Active (1)': 'സജീവം (1)',
    'Active (2)': 'സജീവം (2)',
    'Active (3)': 'സജീവം (3)',
    'Active (4)': 'സജീവം (4)',
    'Completed (0)': 'പൂർത്തിയായത് (0)',
    'Completed (1)': 'പൂർത്തിയായത് (1)',
    'Completed (2)': 'പൂർത്തിയായത് (2)',
    'Completed (3)': 'പൂർത്തിയായത് (3)',
    'Transaction History (0)': 'ഇടപാട് ചരിത്രം (0)',
    'Transaction History (1)': 'ഇടപാട് ചരിത്രം (1)',
    'Transaction History (2)': 'ഇടപാട് ചരിത്രം (2)',
    'Transaction History (3)': 'ഇടപാട് ചരിത്രം (3)',
    'Transaction History (4)': 'ഇടപാട് ചരിത്രം (4)',
    'Transaction History (5)': 'ഇടപാട് ചരിത്രം (5)',
    'Transaction History (6)': 'ഇടപാട് ചരിത്രം (6)',
    'Transaction History (7)': 'ഇടപാട് ചരിത്രം (7)',
    'Transaction History (8)': 'ഇടപാട് ചരിത്രം (8)',

    // Dynamic Ticket options
    '1 Ticket': '1 ടിക്കറ്റ്',
    '2 Tickets': '2 ടിക്കറ്റുകൾ',
    '3 Tickets': '3 ടിക്കറ്റുകൾ',
    '1 Ticket(s)': '1 ടിക്കറ്റ്',
    '2 Ticket(s)': '2 ടിക്കറ്റുകൾ',
    '3 Ticket(s)': '3 ടിക്കറ്റുകൾ',

    // Pre-calculated seats left
    '5 Seats Left': '5 സീറ്റുകൾ ബാക്കി',
    '8 Seats Left': '8 സീറ്റുകൾ ബാക്കി',
    '14 Seats Left': '14 സീറ്റുകൾ ബാക്കി',
    '22 Seats Left': '22 സീറ്റുകൾ ബാക്കി',

    // Home & Dashboard
    'Total Due Amount': 'ആകെ അടയ്ക്കേണ്ട തുക',
    'Active Kuries': 'സജീവ ചിട്ടികൾ',
    'Your Active Kuries': 'നിങ്ങളുടെ സജീവ ചിട്ടികൾ',
    'Pay Chitty Due Now': 'ചിട്ടി ഗഡു ഇപ്പോൾ അടയ്ക്കുക',
    'View Passbook & Ledger': 'പാസ്ബുക്ക് കാണുക',
    'Net Due Payable': 'അടയ്ക്കേണ്ട തുക',
    'Monthly Amount': 'പ്രതിമാസ തുക',
    'Progress': 'പുരോഗതി',
    'Next Due': 'അടുത്ത തീയതി',
    'Status': 'സ്റ്റാറ്റസ്',
    'Closed': 'പൂർത്തിയായി',
    'Closed / Completed': 'പൂർത്തിയായി',
    'Value:': 'മൂല്യം:',
    'Value: ': 'മൂല്യം: ',
    'Scheme Fully Paid & Completed': 'ചിട്ടി പൂർണ്ണമായും അടച്ചു കഴിഞ്ഞു',
    'No schemes found': 'ചിട്ടികളൊന്നും കണ്ടെത്തിയില്ല',

    // Auth & Quick Lock
    'Create Account': 'അക്കൗണ്ട് ഉണ്ടാക്കുക',
    'Sign In Securely': 'സുരക്ഷിതമായി ലോഗിൻ ചെയ്യുക',
    'Full Name': 'പൂർണ്ണ നാമം',
    'Enter full legal name': 'പേര് നൽകുക',
    'Mobile Number': 'മൊബൈൽ നമ്പർ',
    'Enter 10-digit number': '10 അക്ക നമ്പർ നൽകുക',
    'Passcode (4-Digit PIN)': 'പാസ്കോഡ് (4 അക്ക പിൻ)',
    'Enter 4-digit PIN': '4 അക്ക പിൻ നൽകുക',
    'Already have an account? ': 'അക്കൗണ്ട് ഉണ്ടോ? ',
    "Don't have an account? ": 'അക്കൗണ്ട് ഇല്ലേ? ',
    'Sign In': 'ലോഗിൻ',
    'Sign Up': 'രജിസ്റ്റർ',
    'Tap for Biometric Unlock': 'ബയോമെട്രിക് അൺലോക്ക് ചെയ്യുക',
    'Unlock App': 'ആപ്പ് അൺലോക്ക് ചെയ്യുക',
    'Security PIN': 'സെക്യൂരിറ്റി പിൻ',
    'Unlock app using Face ID, Fingerprint or Security PIN': 'ഫേസ് ഐഡി, ഫിംഗർപ്രിന്റ് അല്ലെങ്കിൽ പിൻ ഉപയോഗിച്ച് അൺലോക്ക് ചെയ്യുക',
    'OR ENTER SECURITY PIN': 'അല്ലെങ്കിൽ പിൻ നൽകുക',
    'Sign In with Different Mobile Account': 'മറ്റൊരു അക്കൗണ്ടിൽ ലോഗിൻ ചെയ്യുക',

    // Profile & Menu Options
    'VERIFIED MEMBER': 'അംഗീകൃത അംഗം',
    'Account Details': 'അക്കൗണ്ട് വിവരങ്ങൾ',
    'Personal Details, Nominee & KYC Info': 'വ്യക്തിഗത വിവരങ്ങൾ & കെ.വൈ.സി',
    'Personal Details': 'വ്യക്തിഗത വിവരങ്ങൾ',
    'Bank & UPI Details': 'ബാങ്ക് & യു.പി.ഐ വിവരങ്ങൾ',
    'Linked Bank Account, IFSC & UPI ID': 'ബാങ്ക് അക്കൗണ്ട് & യു.പി.ഐ വിവരങ്ങൾ',
    'Passbook & Transactions': 'പാസ്ബുക്ക് & ഇടപാടുകൾ',
    'Download Statements & Payment Receipts': 'പാസ്ബുക്ക് സ്റ്റേറ്റ്‌മെന്റ് & രസീതുകൾ',
    'App Language, Passcode & Notifications': 'ആപ്പ് ഭാഷ & അറിയിപ്പുകൾ',
    'Help & Support': 'സഹായം & പിന്തുണ',
    '24x7 Customer Care, FAQ & Branch Info': '24x7 കസ്റ്റമർ കെയർ & ശാഖ വിവരങ്ങൾ',
    'Log Out Account': 'ലോഗ് ഔട്ട് ചെയ്യുക',
    'Safely end current active session': 'സെഷൻ സുരക്ഷിതമായി ലോഗ് ഔട്ട് ചെയ്യുക',
    'Edit': 'എഡിറ്റ് ചെയ്യുക',
    'Email Address': 'ഇമെയിൽ വിലാസം',
    'Aadhaar Card': 'ആധാർ കാർഡ്',
    'PAN Card': 'പാൻ കാർഡ്',
    'Nominee Name': 'നോമിനിയുടെ പേര്',
    'Not Added': 'ചേർത്തിട്ടില്ല',
    'Verified': 'പരിശോധിച്ചു',
    'Add / Edit Verification Details': 'വിവരങ്ങൾ എഡിറ്റ് ചെയ്യുക',
    'Save Details': 'സേവ് ചെയ്യുക',
    'Bank Name': 'ബാങ്കിന്റെ പേര്',
    'Account Number': 'അക്കൗണ്ട് നമ്പർ',
    'IFSC Code': 'ഐ.എഫ്.എസ്.സി കോഡ്',
    'UPI ID': 'യു.പി.ഐ ഐ.ഡി',
    'Support & Help': 'സഹായവും പിന്തുണയും',
    'Customer Care': 'കസ്റ്റമർ കെയർ',
    'Branch Locator': 'ശാഖകൾ',

    // Settings Screen
    'General Preferences': 'പൊതു മുൻഗണനകൾ',
    'App Language': 'ആപ്പ് ഭാഷ',
    'Dark Mode': 'ഡാർക്ക് മോഡ്',
    'Adjust interface color theme': 'തീം വർണ്ണം മാറ്റുക',
    'Security & Privacy': 'സുരക്ഷയും സ്വകാര്യതയും',
    'Biometric & PIN Lock': 'ബയോമെട്രിക് & പിൻ ലോക്ക്',
    'Secure app startup authentication': 'ആപ്പ് സ്റ്റാർട്ടപ്പ് സുരക്ഷ',
    'SMS & Push Notifications': 'എസ്.എം.എസ് & പുഷ് അറിയിപ്പുകൾ',
    'Get installment due reminders & alerts': 'ചിട്ടി ഗഡു അറിയിപ്പുകൾ നേടുക',
    'Privacy Policy': 'സ്വകാര്യതാ നയം',
    'Terms & Conditions': 'നിബന്ധനകൾ & വ്യവസ്ഥകൾ',
    'Regulated & Licensed Chitty Fund': 'ലൈസൻസുള്ള ചിട്ടി ഫണ്ട്',

    // Kuri Details & Catalog & Application
    'Kuri Application': 'ചിട്ടി അപേക്ഷ',
    'Application Submitted!': 'അപേക്ഷ സമർപ്പിച്ചു!',
    'Go to My Kuris': 'എന്റെ ചിട്ടികളിലേക്ക് പോവുക',
    'Total Scheme Value:': 'ആകെ പദ്ധതി തുക:',
    'Select Number of Tickets': 'ടിക്കറ്റുകളുടെ എണ്ണം തിരഞ്ഞെടുക്കുക',
    'KYC & Verification': 'കെ.വൈ.സി & വിവരങ്ങൾ',
    'Your verified profile KYC details (Aadhaar & PAN) will be attached automatically.': 'നിങ്ങളുടെ സ്ഥിരീകരിച്ച കെ.വൈ.സി വിവരങ്ങൾ തനിയെ ചേർക്കുന്നതാണ്.',
    'Submit Kuri Application': 'അപേക്ഷ സമർപ്പിക്കുക',
    'Kuri Details': 'ചിട്ടി വിവരങ്ങൾ',
    'Installment History': 'ഗഡുക്കളുടെ ചരിത്രം',
    'Paid on': 'അടച്ച തീയതി',
    'Auction & Dividend': 'ലേലവും ഡിവിഡന്റും',
    'Next Auction Date': 'അടുത്ത ലേല തീയതി',
    'Average Dividend Earned': 'ലഭിച്ച ശരാശരി ഡിവിഡന്റ്',
    'Total Members Won': 'തുക ലഭിച്ച അംഗങ്ങൾ',
    '12 Members': '12 അംഗങ്ങൾ',
    'Organizer Support': 'ഓർഗനൈസർ സഹായം',
    'Call +91 98470 12345 for help': 'സഹായത്തിന് +91 98470 12345 വിളിക്കുക',
    'Chitty Completed & Fully Paid': 'ചിട്ടി പൂർണ്ണമായും അടച്ചു കഴിഞ്ഞു',
    'Pay Next Installment': 'അടുത്ത ഗഡു അടയ്ക്കുക',
    'Downloading Chitty Passbook PDF...': 'ചിട്ടി പാസ്ബുക്ക് PDF ഡൗൺലോഡ് ചെയ്യുന്നു...',
    'Chit Amount': 'ചിട്ടി തുക',
    'Total Installments': 'ആകെ ഗഡുക്കൾ',
    'Auction Discount': 'ലേല ലേലം ഡിസ്കൗണ്ട്',
    'Bonus Discount': 'ബോണസ് ഡിസ്കൗണ്ട്',
    'Dividend Benefit': 'ഡിവിഡന്റ് ആനുകൂല്യം',
    'Fine / Late Fee': 'ഫൈൻ / ലേറ്റ് ഫീ',
    'Payable Amount': 'അടയ്ക്കേണ്ട തുക',
    'Installments Ledger': 'ഗഡുക്കളുടെ ലെഡ്ജർ',
    'Join Scheme Now': 'ചിട്ടിയിൽ ചേരുക',
    'View Auction History': 'ലേല ചരിത്രം കാണുക',
    'Search by scheme name or amount...': 'ചിട്ടി പേരോ തുകയോ തിരയുക...',
    'Search by Chitty code, TXN ID or met...': 'ചിട്ടി കോഡ്, ഐ.ഡി തിരയുക...',
    'Apply Now': 'അപേക്ഷിക്കുക',
    'Apply for Chitty': 'ചിട്ടി അപേക്ഷ',
    'Seats Left': 'സീറ്റുകൾ ബാക്കി',
    'Total Value': 'ആകെ തുക',
    'Monthly Installment': 'പ്രതിമാസ ഗഡു',
    'Duration': 'കാലാവധി',
    'Apply & Join Kuri →': 'ചിട്ടിയിൽ ചേരുക →',
    'Apply & Join Kuri': 'ചിട്ടിയിൽ ചേരുക',

    // Passbook & Payments & PDF Receipts
    'Chitty Payment': 'ചിട്ടി അടയ്ക്കൽ',
    'Monthly Base Amount': 'പ്രതിമാസ ഗഡു തുക',
    'Auction Dividend Discount': 'ലേല ഡിവിഡന്റ് ഡിസ്കൗണ്ട്',
    'Early Payment Bonus': 'ഏർളി പേയ്‌മെന്റ് ബോണസ്',
    'Recent Payment History': 'സമീപകാല ഇടപാട് ചരിത്രം',
    'All Ledger': 'എല്ലാ ഇടപാടുകളും',
    'Successful Paid': 'അടച്ചവ',
    'Upcoming / Due': 'അടയ്ക്കാനുള്ളവ',
    'All Schemes': 'എല്ലാ പദ്ധതികളും',
    'Transaction History': 'ഇടപാട് ചരിത്രം',
    'Export Statement': 'സ്റ്റേറ്റ്‌മെന്റ് ഡൗൺലോഡ്',
    'Pending (Due)': 'അടയ്ക്കാനുണ്ട്',
    'Due Date:': 'അവസാന തീയതി:',
    'Total Paid to Date': 'ഇതുവരെ അടച്ച തുക',
    'Pending Installment Due': 'അടയ്ക്കാനുള്ള ഗഡു',
    'Download Passbook PDF': 'പാസ്ബുക്ക് PDF ഡൗൺലോഡ് ചെയ്യുക',
    'Pay Now': 'ഇപ്പോൾ അടയ്ക്കുക',
    'Receipt': 'രസീത്',
    'Paid': 'അടച്ചു',
    'PAID': 'അടച്ചു',
    'Due': 'അടയ്ക്കണം',
    'DUE': 'അടയ്ക്കണം',
    'Select Payment Method': 'പേയ്‌മെന്റ് മാർഗ്ഗം തിരഞ്ഞെടുക്കുക',
    'UPI Instant Transfer': 'യു.പി.ഐ ഇൻസ്റ്റന്റ് ട്രാൻസ്ഫർ',
    'Debit Card / Net Banking': 'ഡെബിറ്റ് കാർഡ് / നെറ്റ് ബാങ്കിംഗ്',
    'Proceed to Pay': 'അടയ്ക്കാൻ മുന്നോട്ട് പോകുക',
    'Payment Successful!': 'പേയ്‌മെന്റ് വിജയിച്ചു!',
    'Transaction ID': 'ഇടപാട് ഐ.ഡി',
    'Paid Amount': 'അടച്ച തുക',
    'Download Receipt': 'രസീത് ഡൗൺലോഡ് ചെയ്യുക',
    'Back to Home': 'ഹോമിലേക്ക് മടങ്ങുക',
    'Done': 'പൂർത്തിയായി',
    'Scheme Name': 'ചിട്ടി പേര്',
    'Installment': 'ഗഡു',
    'Payment Mode': 'പേയ്‌മെന്റ് മാർഗ്ഗം',
    'Date & Time': 'തീയതി & സമയം',
    'Receipt downloaded to downloads folder!': 'രസീത് ഡൗൺലോഡ് ചെയ്തു!',
  };

  /// Fast O(1) Constant-Time Lookup with no runtime regex matching
  String tr(String text) {
    if (!isMalayalam) return text;
    return _ml[text] ?? text;
  }
}

final appLocalizationsProvider = Provider<AppLocalizations>((ref) {
  final settings = ref.watch(settingsProvider);
  return AppLocalizations(settings.language);
});
